name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install -g html-minifier-terser
          npm install -g clean-css-cli
          npm install -g terser

      - name: Minify HTML
        run: |
          # Minify main HTML files
          if [ -f "index.html" ]; then
            html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o index.html index.html
          fi

          # Minify pages HTML files
          for file in pages/*.html; do
            if [ -f "$file" ]; then
              html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o "$file" "$file"
            fi
          done

          # Minify blog posts HTML files
          for file in blog-posts/*.html; do
            if [ -f "$file" ]; then
              html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o "$file" "$file"
            fi
          done

      - name: Minify CSS
        run: |
          # Minify main CSS file
          if [ -f "styles.css" ]; then
            cleancss -o styles.css styles.css
          fi

          # Minify CSS files in css directory
          for file in css/*.css; do
            if [ -f "$file" ]; then
              cleancss -o "$file" "$file"
            fi
          done

      - name: Minify JS
        run: |
          # Minify main JS file
          if [ -f "script.js" ]; then
            terser script.js -o script.js -c -m
          fi

          # Minify JS files in js directory
          for file in js/*.js; do
            if [ -f "$file" ]; then
              terser "$file" -o "$file" -c -m
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
