name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install -g html-minifier-terser
          npm install -g clean-css-cli
          npm install -g terser

      - name: Minify HTML (ignore missing files)
        run: |
          html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o index.html index.html || true
          for file in pages/*.html; do
            [ -e "$file" ] && html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o "$file" "$file" || true
          done

      - name: Minify CSS (ignore missing files)
        run: |
          cleancss -o styles.css styles.css || true
          for file in css/*.css; do
            [ -e "$file" ] && cleancss -o "$file" "$file" || true
          done

      - name: Minify JS (ignore missing files)
        run: |
          terser script.js -o script.js -c -m || true
          for file in js/*.js; do
            [ -e "$file" ] && terser "$file" -o "$file" -c -m || true
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
